name : Build

on :
  [ push, pull_request， workflow_dispatch ]

jobs :
  build-windows :
    runs-on : windows-latest
    steps :
      - uses : actions/checkout@v2
      - uses : actions/setup-node@v2
        with :
          node-version : 16
          cache : 'yarn'
      - name : Install deps
        run : yarn
      - name : Build windows nsis installer
        run : npm run nsis
      - name : Build windows 7zip protable version
        run : npm run 7zip
      - uses : actions/upload-artifact@v2
        with :
          path : |
            packaged/wnr-*-Setup-x64.exe
            packaged/wnr-*-Setup-ia32.exe
            packaged/wnr-*-Win-x64.7z
            packaged/wnr-*-Win-ia32.7z

  build-macos :
    runs-on : macos-latest
    steps :
      - uses : actions/checkout@v2
      - uses : actions/setup-node@v2
        with :
          node-version : 16
          cache : 'yarn'
      - name : Install deps
        run : yarn
      - name : Build macos version
        run : npm run mac
      - uses : actions/upload-artifact@v2
        with :
          path : |
            packaged/wnr-*-MacOS-x64.dmg
            packaged/wnr-*-MacOS-arm64.dmg

  build-linux :
    runs-on : ubuntu-latest
    steps :
      - uses : actions/checkout@v2
      - uses : actions/setup-node@v2
        with :
          node-version : 16
          cache : 'yarn'
      - name : Install deps
        run : yarn
      - name : Build AppImage
        run : npm run appimage
      - uses : actions/upload-artifact@v2
        with :
          path : packaged/wnr-*-Linux.AppImage
